language: node_js
node_js:
- '0.10'
cache:
  apt: true
  directories:
  - $HOME/.titanium
  - $HOME/.nvm
env:
  global:
  # TI_USER and TI_PASS
  - secure: "v9fP7FjFo7xCEseFUDjORhtPZf0haqipNnS7NMbr/liSgCqA+E3brra/4o4RUBOP8Ll0OryKFxXBW6RM19gNSpt0tj8oiA6QYZKOapiaKHJlGd/U3cVcRo6MmIFPBO1MTcQQpCnD4D+X82aSRzAXG5reasteFLo3/dbdPCao/+8="
before_script:
- npm install -g alloy glob jade coffee-script
- npm install -g 'git://github.com/appcelerator/titanium.git#642155f'
- titanium login "$TI_USER" "$TI_PASS"
- ti sdk install -b 3_2_X -d 3.2.0.v20131126111643
- sudo apt-get update
- sudo apt-get install openjdk-7-jdk
- titanium build -p mobileweb --sdk 3.2.0.v20131126111643
- ruby -run -e httpd build/mobileweb -p 8020 > /dev/null 2>&1 &
- sleep 1
script: phantomjs --web-security=no --local-to-remote-url-access=yes specs/test_runner.js
